import os
import asyncio
import logging
from datetime import datetime
from pathlib import Path
from sqlalchemy import select, and_
from sqlalchemy.ext.asyncio import AsyncSession

# 导入项目模块
from backend.database.connection import AsyncSessionLocal
from backend.models.mcp_service import MCPService, ServiceStatus
from backend.mcpybarra_core.framework.mcp_swe_flow.nodes.swe_generator import swe_generate_node
from backend.config.settings import settings

# 配置日志
logger = logging.getLogger("worker.service")

async def process_pending_services():
    """
    核心工作函数：
    1. 查找所有状态为 GENERATING 且 代码为空 的任务
    2. 逐个处理
    """
    async with AsyncSessionLocal() as session:
        try:
            # 1. 查找待处理任务
            # 修正：根据你的模型定义，新任务默认是 GENERATING
            # 我们增加一个条件：code 为空，确保只处理新任务，不重复处理正在跑的任务
            result = await session.execute(
                select(MCPService).where(
                    and_(
                        MCPService.status == ServiceStatus.GENERATING,
                        (MCPService.code == None) | (MCPService.code == "")
                    )
                )
            )
            pending_services = result.scalars().all()
            
            if not pending_services:
                return 

            logger.info(f"🚀 Found {len(pending_services)} new services to process")

            # 2. 逐个处理任务
            for service in pending_services:
                await process_single_service(session, service)
                
        except Exception as e:
            logger.error(f"❌ Error in process_pending_services: {e}", exc_info=True)


async def process_single_service(session: AsyncSession, service: MCPService):
    """处理单个服务生成流程"""
    service_id = service.id
    logger.info(f"👉 Starting processing for service: {service.name} ({service_id})")

    try:
        # Step 1: 更新时间戳，表示 Worker 正在活跃处理
        service.updated_at = datetime.utcnow()
        await session.commit()
        
        # Step 2: 准备生成参数
        state = {
            "user_input": service.original_requirement,
            "project_path": service.file_path or "",  
            "demo_mode": False,
            "verbose": True
        }
        
        logger.info(f"🤖 Generating code with LLM for {service_id}...")

        # Step 3: 调用生成逻辑
        # 这可能会花费一些时间
        result_state = await swe_generate_node(state)
        
        generated_code = result_state.get("implementation_code", "")
        test_code = result_state.get("test_code", "")
        error = result_state.get("error")

        if error:
            raise Exception(f"LLM Generation failed: {error}")

        if not generated_code:
            raise Exception("LLM returned empty code")

        logger.info(f"✅ Code generated successfully for {service_id}")

        # Step 4: 保存代码到文件系统
        # 确保目录存在
        # 如果 file_path 为空，使用默认路径
        if not service.file_path:
             service_dir = Path(settings.SERVICES_DIR) / service_id
        else:
             service_dir = Path(service.file_path)
             
        service_dir.mkdir(parents=True, exist_ok=True)
        
        # 保存主代码
        main_file = service_dir / "main.py"
        with open(main_file, "w", encoding="utf-8") as f:
            f.write(generated_code)
            
        # 保存测试代码
        if test_code:
            test_file = service_dir / "test_main.py"
            with open(test_file, "w", encoding="utf-8") as f:
                f.write(test_code)
        
        # 保存 README
        readme_file = service_dir / "README.md"
        with open(readme_file, "w", encoding="utf-8") as f:
            f.write(f"# {service.name}\n\n{service.description}\n\nGenerated by MCP-SWE-Agent")

        # Step 5: 更新数据库状态
        # 重新获取对象防止 Session 冲突
        result = await session.execute(select(MCPService).where(MCPService.id == service_id))
        service = result.scalar_one()

        service.code = generated_code
        # 修正：模型里没有 COMPLETED，改为 READY
        service.status = ServiceStatus.READY 
        service.file_path = str(service_dir)
        service.updated_at = datetime.utcnow()
        
        await session.commit()
        logger.info(f"🎉 Service {service_id} processing COMPLETED (Status: READY)!")

    except Exception as e:
        logger.error(f"❌ Failed to process service {service_id}: {e}", exc_info=True)
        
        try:
            result = await session.execute(select(MCPService).where(MCPService.id == service_id))
            service = result.scalar_one()
            
            service.status = ServiceStatus.FAILED
            service.total_errors += 1
            service.updated_at = datetime.utcnow()
            if service.description:
                service.description += f"\n\n[Error Log]: {str(e)}"
            
            await session.commit()
            logger.info(f"⚠️ Marked service {service_id} as FAILED")
        except Exception as db_e:
            logger.critical(f"🔥 Critical DB error: {db_e}")
